# Generated by Django 5.0.7 on 2025-01-08 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Matni')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project1.flower', verbose_name='Gul nomi')),
            ],
            options={
                'verbose_name': 'Izoh ',
                'verbose_name_plural': 'Izohlar',
                'ordering': ['-id'],
            },
        ),
    ]
